### ISSUE TITLE
How to Properly Set it up with HAProxy?

### ISSUE THREAD

**Issue by g0ld3lux** [ethical-jobs/aphex#2]
Hi i want to scale This Container at the same time load balance...

I manage to Run this Container with no Problem...

```
version: '2'
services:
    web:
        build: ./web
        container_name: sandbox-web
        volumes:
        - ./laravel:/var/www
        - ./web/config/supervisord.conf:/etc/supervisord.conf
        - ./web/config/nginx.conf:/etc/nginx/nginx.conf
        - ./web/config/php.ini:/usr/local/etc/php/conf.d/php-fpm.ini
        ports:
        - "80:80"
```
when i do docker-compose up
i see laravel site up and running...

but as i try to do scaling with docker...

im facing hardship making it work...

but i manage to make it work at this repo
https://github.com/andrewmclagan/nginx-hhvm-docker

this is my docker-compose 
https://gist.github.com/g0ld3lux/8d7e5aaf812f028c2a289e65073274a5

i only manage to make it work using stack file

i cant make it work on docker-compose v2

but aphex on the other hand i cant even use the stackfile and v2 syntax

Can You Share me Your Docker compose file?
